# Generated by Django 5.1.1 on 2024-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_desc', models.CharField(max_length=500)),
                ('project_language', models.CharField(max_length=255)),
                ('project_image', models.CharField(default='https://raw.githubusercontent.com/Bradon-Barfuss/C-Sharp-Programs/main/Invoice%20System/InvoiceMainMenuPicture.png', max_length=500)),
                ('github_link', models.URLField(blank=True, max_length=500, null=True)),
                ('project_highlights', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('implementation_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
