# Generated by Django 5.1.1 on 2024-10-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_image',
            field=models.CharField(default='https://raw.githubusercontent.com/Bradon-Barfuss/C-Sharp-Programs/main/Invoice%20System/InvoiceMainMenuPicture.png', max_length=500),
        ),
    ]
