# Generated by Django 5.1.1 on 2024-10-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_portfolio_features_portfolio_implementation_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
